apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany 
  nfs:
    path: /database
    server: 192.168.254.114 
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: nfs-storage